//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketSystem.MySqlDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.sales = new HashSet<sale>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int vendor_id { get; set; }
        public int measure_id { get; set; }
        public int type_id { get; set; }
        public decimal price { get; set; }
    
        public virtual measure measure { get; set; }
        public virtual vendor vendor { get; set; }
        public virtual products_types products_types { get; set; }
        public virtual ICollection<sale> sales { get; set; }
    }
}
