//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketSystem.MySqlDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int supermarket_id { get; set; }
        public int product_id { get; set; }
        public int quantity { get; set; }
        public decimal unit_price { get; set; }
        public decimal total_sum { get; set; }
    
        public virtual product product { get; set; }
        public virtual supermarket supermarket { get; set; }
    }
}
