//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketSystem.MySqlDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class supermarket
    {
        public supermarket()
        {
            this.sales = new HashSet<sale>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int town_id { get; set; }
    
        public virtual ICollection<sale> sales { get; set; }
        public virtual town town { get; set; }
    }
}
