//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketSystem.MySqlDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class town
    {
        public town()
        {
            this.supermarkets = new HashSet<supermarket>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<supermarket> supermarkets { get; set; }
    }
}
