//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketSystem.MySqlDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor
    {
        public vendor()
        {
            this.products = new HashSet<product>();
            this.vendor_expenses = new HashSet<vendor_expenses>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<product> products { get; set; }
        public virtual ICollection<vendor_expenses> vendor_expenses { get; set; }
    }
}
