//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketSystem.OracleDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int ID { get; set; }
        public int VENDORID { get; set; }
        public string NAME { get; set; }
        public int MEASUREID { get; set; }
        public int TYPEID { get; set; }
        public decimal PRICE { get; set; }
    
        public virtual MEASURE MEASURE { get; set; }
        public virtual PRODUCTSTYPE PRODUCTSTYPE { get; set; }
        public virtual VENDOR VENDOR { get; set; }
    }
}
